dependencies:
  - conda-forge::numpy=1.19.2
  - conda-forge::pip
  - conda-forge::python=3.9
  - pip:
      - matplotlib==3.4.3
      - astropy
      - scipy
      - legwork
      - seaborn
      - tables
      - pandas
